/* GENERATED by build.mjs. Offline browser and video token adapter. */
window.MoltsetsTokens = {
  "version": "1.0.0",
  "status": "source-matched with documented production extensions",
  "source": {
    "url": "https://moltsets.com/",
    "date": "2026-09-08",
    "css": "../raw/sources/2026-09-08-moltsets-brand/moltsets-base.css"
  },
  "colors": {
    "brand": "#F4805D",
    "brand-stroke": "#F97316",
    "brand-tint": "#F58D6D",
    "brand-dim": "#DC7354",
    "brand-bg": "#39291D",
    "bg-base": "#0A0B0E",
    "bg-elevated": "#1E1E1E",
    "bg-terminal": "rgba(244,128,93,0.10)",
    "bg-chip": "#374151",
    "bg-chip-alt": "#1F2937",
    "fg-primary": "#F1F5F9",
    "fg-secondary": "#CBD5E1",
    "fg-muted": "#94A3B8",
    "fg-subdued": "#99A1AF",
    "fg-bright": "#FFFFFF",
    "fg-accent": "#F4805D",
    "success": "#34D399",
    "hint": "#FDE047",
    "danger": "#F87171",
    "purple": "#9747FF",
    "divider": "rgba(206,206,206,0.5)",
    "divider-dim": "rgba(206,206,206,0.25)"
  },
  "fonts": {
    "source": {
      "family": "SF Mono",
      "weights": [
        300,
        400,
        500,
        600,
        700,
        800
      ],
      "usage": "Reference archive only; no production redistribution licence supplied"
    },
    "production": {
      "family": "Roboto Mono",
      "file": "RobotoMono-Variable.ttf",
      "weight": "100 700",
      "license": "RobotoMono-OFL.txt",
      "fallback": "ui-monospace, monospace"
    }
  },
  "type": {
    "display": {
      "size": 88,
      "line": 1.08,
      "weight": 700,
      "tracking": -0.045
    },
    "headline": {
      "size": 64,
      "line": 1.12,
      "weight": 700,
      "tracking": -0.035
    },
    "title": {
      "size": 44,
      "line": 1.2,
      "weight": 600,
      "tracking": -0.025
    },
    "body": {
      "size": 32,
      "line": 1.5,
      "weight": 400,
      "tracking": -0.02
    },
    "label": {
      "size": 24,
      "line": 1.4,
      "weight": 500,
      "tracking": 0.02
    },
    "micro": {
      "size": 20,
      "line": 1.4,
      "weight": 400,
      "tracking": 0
    }
  },
  "layout": {
    "unit": 8,
    "safe": 72,
    "radius": 0,
    "rule": 2,
    "corner": 16
  },
  "motion": {
    "fps": 30,
    "duration": 4000,
    "enter": 360,
    "stagger": 160,
    "distance": 24,
    "ease": [
      0.22,
      1,
      0.36,
      1
    ],
    "mascotTimes": [
      0,
      150,
      240,
      320,
      410,
      490,
      550
    ],
    "thinkingHolds": [
      95,
      105,
      260,
      280,
      190,
      105,
      90
    ]
  }
};
