// Editable composition sources. Rebuild HTML with `node brand/build.mjs`.
// Demonstration copy is not an approved content campaign. Metric slots stay empty.
import {logo,eyebrow,terminal,callout,quote,metric,step,node,connector,code,prompt,footer,mascot,lowerThird} from '../components.mjs';
const head=(text)=>`<div class="ms-spread" data-enter="0">${logo()}${eyebrow(text)}</div>`;
const arrow=t=>`<div data-enter="${t}">${connector().replace('<path ','<path data-draw="'+t+'" ')}</div>`;
export const scenes=[
  {id:'cover',title:'Editorial cover',width:1080,height:1350,classes:'cover-layout texture',
    body:`${head('field notes / 01')}<div class="cover-head ms-stack" data-enter="180"><h1 class="ms-display">Data for<br><em class="ms-accent">AI workflows.</em></h1><p class="ms-body ms-secondary">Search. Enrich.<br>Build with context.</p></div><div class="cover-console" data-enter="480">${terminal('moltsets / field notes',`${mascot('..',true)}<div class="ms-stack"><h2 class="ms-title">Built for<br>your stack.</h2><p class="ms-body ms-secondary">A visual introduction to search and enrichment.</p></div>`,true)}</div>${footer('MoltSets / visual study','01')}`},
  {id:'quote',title:'Source quotation',width:1080,height:1350,classes:'quote-layout',
    body:`${head('from the website')}<div data-enter="160">${quote('API-first, no dashboard','MoltSets website · 08 Sep 2026')}</div><p class="quote-context ms-body ms-secondary" data-enter="520">Search and enrichment,<br>inside your AI stack.</p><div class="ms-grow"></div><div data-enter="760">${prompt('built for workflows')}</div>${footer('Source: moltsets.com','02')}`},
  {id:'carousel-detail',title:'Carousel detail',width:1080,height:1350,classes:'detail-layout',
    body:`${head('workflow notes')}<h1 class="ms-headline" data-enter="160">From a list<br>to <em class="ms-accent">useful context.</em></h1><div data-enter="400">${terminal('a conceptual sequence',`${step('01','Search','Define the prospect you need.')}${step('02','Enrich','Add the missing contact data.')}${step('03','Use','Bring that context into your workflow.')}`,true)}</div>${callout('A sequence explains what happens next.')}${footer('MoltSets / conceptual example','03')}`},
  {id:'workflow',title:'Workflow / motion scene',width:1920,height:1080,classes:'workflow-layout texture',
    body:`${head('workflow / 01')}<h1 class="ms-headline" data-enter="160">Give your workflow<br><em class="ms-accent">the context it needs.</em></h1><div data-enter="360">${terminal('search + enrichment / conceptual map',`<div class="workflow-diagram"><div class="ms-grow" data-enter="520">${node('01 / input','Search','Find relevant prospects.')}</div>${arrow(860)}<div class="ms-grow" data-enter="1000">${node('02 / context','Enrich','Add missing contact data.',true)}</div>${arrow(1340)}<div class="ms-grow" data-enter="1480">${node('03 / destination','Use','Bring it into your stack.')}</div></div><div data-enter="1880">${prompt('context, ready for your next step')}</div>`)}</div><div data-enter="2240">${callout('A conceptual sequence. Not a product interface or API contract.')}</div>${footer('MoltSets / motion study','01 / 03')}`},
  {id:'lower-third',title:'Transparent lower third',width:1920,height:1080,classes:'lower-third-layout transparent',
    body:`<div data-enter="200">${lowerThird('Adam Robinson','MoltSets')}</div>`},
  {id:'story',title:'Vertical title scene',width:1080,height:1920,classes:'story-layout texture',
    body:`${head('field notes')}<div class="ms-stack" data-enter="180"><h1 class="ms-display">Search.<br>Enrich.<br><em class="ms-accent">Build.</em></h1><p class="ms-body ms-secondary">Contact data for<br>AI workflows.</p></div><div class="ms-row" data-enter="480">${mascot('..',true)}<p class="ms-body ms-coral">moltsets<br><span class="ms-muted">/_</span></p></div><div data-enter="800">${terminal('one idea at a time',callout('Bring the missing context into your stack.'),true)}</div>${footer('MoltSets / vertical study','01')}`},
  {id:'scorecard',title:'Evidence / metric template',width:1080,height:1080,classes:'scorecard-layout',
    body:`${head('evidence template')}<h1 class="ms-headline" data-enter="160">A claim needs<br><em class="ms-accent">a source.</em></h1><div class="metrics" data-enter="440">${metric('—','Primary metric','Insert source + period')}${metric('—','Comparison metric','Use a comparable basis')}</div><div data-enter="720">${callout('Replace these empty slots with verified evidence before publishing.')}</div>${footer('Template / no performance claim','04')}`}
];
