#!/usr/bin/env python3
"""File an already-exported RB2B LinkedIn table; no network calls or overwrites.

The original 200-post sample remains immutable. Reuse its Markdown paths for
identical overlaps, and add exact readable bodies for the other Adam records.
--check verifies every generated byte without writing anything.
"""
import argparse
import collections
import datetime as dt
import hashlib
import json
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
BASE = Path('raw/sources/2026-09-08-linkedin-rb2b')
ORIGINAL = Path('raw/sources/2026-09-08-linkedin/posts.normalized.json')
TABLE = '6f0691cb-161b-41ec-8de7-afa083d9028c'
WORKSPACE = '9ef2c28f-4021-4e21-881b-5af6a5213350'
TABLE_URL = f'https://dev.oxygen-agent.com/workspaces/{WORKSPACE}/tables/{TABLE}'


def sha(body):
    return hashlib.sha256(body.encode('utf-8')).hexdigest()


def serialize(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + '\n'


def file_capture(check=False):
    def save(relative, body):
        path = ROOT / relative
        encoded = body.encode('utf-8')
        if path.exists():
            if path.read_bytes() != encoded:
                raise ValueError(f'Refusing to overwrite changed source: {relative}')
        elif check:
            raise ValueError(f'Missing source artifact: {relative}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open('xb') as handle:
                handle.write(encoded)

    receipt = json.loads((ROOT / BASE / 'export-receipt.json').read_text())
    assert receipt['workspace_id'] == WORKSPACE and receipt['table_id'] == TABLE
    rows, origins, row_ids, totals = [], {}, set(), set()
    for number, page in enumerate(receipt['pages']):
        path = Path(page['response_path'])
        assert path.parent == BASE / 'responses'
        envelope = json.loads((ROOT / path).read_text())
        assert envelope['ok'] is True
        data = envelope['data']
        assert data['table']['id'] == TABLE and data['totalCountMode'] == 'exact'
        assert data['returnedCount'] == len(data['rows']) == page['rows']
        assert data['hasMore'] == (number < len(receipt['pages']) - 1)
        totals.add(data['totalCount'])
        for row in data['rows']:
            post_id = row['activity_id']
            assert isinstance(post_id, str) and post_id.isdigit()
            assert post_id not in origins and row['_row_id'] not in row_ids
            assert isinstance(row['content'], str)
            assert urlparse(row['post_url']).hostname == 'www.linkedin.com'
            assert post_id in row['post_url']
            dt.datetime.fromisoformat(row['posted_at'].replace('Z', '+00:00'))
            row_ids.add(row['_row_id'])
            origins[post_id] = path.as_posix()
            rows.append(row)
    assert totals == {len(rows)}, 'Missing rows or changing export scope'
    original = {p['id']: p for p in json.loads((ROOT / ORIGINAL).read_text())}
    assert len(original) == 200
    authored, others = [], []
    for row in rows:
        author = urlparse(row['author_url'])
        if author.hostname == 'www.linkedin.com' and author.path.rstrip('/') == '/in/retentionadam':
            assert row['author_name'] == 'Adam Robinson'
            authored.append(row)
        else:
            others.append(row)
    authored.sort(key=lambda r: (r['posted_at'], r['activity_id']), reverse=True)
    assert set(original) <= {r['activity_id'] for r in authored}
    normalized, overlaps, missing_bodies = [], [], []
    for rank, row in enumerate(authored, 1):
        post_id, date, content = row['activity_id'], row['posted_at'], row['content']
        source = origins[post_id]
        previous = original.get(post_id)
        if previous:
            assert content == previous['content'], f'Changed overlap text: {post_id}'
            assert date == previous['source_date'], f'Changed overlap date: {post_id}'
            path = Path(previous['markdown_path'])
            old_body = (ROOT / path).read_text().split('## Exact post text\n\n', 1)[1].split('\n\n## Source Notes\n', 1)[0]
            assert old_body == content
            overlaps.append(post_id)
        else:
            path = BASE / 'posts' / f'{date[:10]}-{post_id}.md'
            body = '\n'.join([
                '---', 'type: source', 'status: captured', 'owner: adam',
                'created: 2026-09-08', 'updated: 2026-09-08',
                f'source_date: {json.dumps(date)}', f'post_id: {json.dumps(post_id)}',
                f'source_url: {json.dumps(row["post_url"])}',
                'source_author: "Adam Robinson"',
                'attribution: "Attributed by the archived table to Adam’s LinkedIn profile; writing process unverified"',
                'public_use: "Public-source research; new first-person copy requires approval"',
                f'sources: [{json.dumps(source)}]', 'tags: [source, linkedin, adam-robinson, rb2b-archive]',
                '---', '', f'# LinkedIn post — {date[:10]} — {post_id}', '',
                f'- Published: {date}', f'- Source: {row["post_url"]}',
                '- Capture: 2026-09-08; existing Oxygen dev / RB2B table, read-only export.',
                f'- Source row ID: {row["_row_id"]}',
                f'- Body availability: {"present" if content.strip() else "empty in the source table; text not recovered"}.',
                '', '## Exact post text', '', content, '', '## Source Notes', '',
                f'Exact table row retained in `{source}` (activity ID `{post_id}`).',
                'Text is unchanged from the table. Its upstream scraper payload and media are not columns in this export.',
                'Engagement is a source-table snapshot; the export time does not establish when it was measured.',
                'Guest statements, quoted material and historical metrics retain their original subjects and periods.', '',
            ])
            save(path, body)
        if not content.strip():
            missing_bodies.append(post_id)
        normalized.append({
            'rank': rank, 'id': post_id, 'source_date': date, 'source_url': row['post_url'],
            'author': row['author_name'], 'author_identifier': 'retentionadam',
            'content': content, 'body_available': bool(content.strip()), 'body_sha256': sha(content),
            'source_file': source, 'source_row_id': row['_row_id'], 'markdown_path': path.as_posix(),
            'previously_selected': previous is not None,
            'engagement': {key: row[key] for key in ('likes', 'comments', 'shares')},
        })
    save(BASE / 'posts.normalized.json', serialize(normalized))
    audit = {
        'table_rows': len(rows), 'unique_activity_ids': len(origins), 'pagination_exhausted': True,
        'adam_records': len(authored), 'adam_nonempty_bodies': len(authored) - len(missing_bodies),
        'other_author_records': len(others), 'original_200_overlaps': len(overlaps),
        'overlap_text_and_dates_identical': True, 'added_adam_records': len(authored) - len(overlaps),
        'added_nonempty_bodies': len(authored) - len(overlaps) - len(missing_bodies),
        'empty_body_ids': sorted(missing_bodies), 'newest': normalized[0]['source_date'],
        'oldest': normalized[-1]['source_date'],
        'year_counts': dict(sorted(collections.Counter(r['source_date'][:4] for r in normalized).items())),
        'other_authors': dict(sorted(collections.Counter(r['author_name'] for r in others).items())),
        'excluded_other_author_records': [{key: r[key] for key in ('activity_id', 'author_name', 'author_url', 'post_url')} for r in others],
        'all_history_claim': 'Complete export of the available table, not proof of every LinkedIn post ever published.',
    }
    save(BASE / 'comparison.json', serialize(audit))
    overview = ['# LinkedIn archive — RB2B supplement', '',
                f'{len(authored)} unique Adam-profile records across the combined archive; {len(authored)-len(missing_bodies)} have nonempty text.', '',
                f'{len(authored)-len(overlaps)} records extend the original 200-post sample. All {len(rows)} table rows remain in the exact export; {len(others)} other-author records are excluded from Adam’s corpus.', '',
                'The additional posts are captured for retrieval and have not yet received a full synthesis pass.', '',
                '## Browse by publication year', '']
    for year, count in audit['year_counts'].items():
        overview.append(f'- [[{BASE}/by-year/{year}|{year} — {count} posts]]')
        lines = [f'# Adam-profile LinkedIn archive — {year}', '',
                 'Body links preserve source text. An empty-body label means the table has no text for that post.', '',
                 '| Published | Post ID and exact source |', '| --- | --- |']
        for post in normalized:
            if post['source_date'].startswith(year):
                label = post['id'] + ('' if post['body_available'] else ' — empty body')
                lines.append(f'| {post["source_date"][:10]} | [[{post["markdown_path"][:-3]}|{label}]] |')
        lines += ['', f'[[{BASE}/manifest|Capture manifest]]', '']
        save(BASE / 'by-year' / f'{year}.md', '\n'.join(lines))
    overview += ['', f'[[{BASE}/manifest|Capture manifest and limitations]]', '']
    save(BASE / 'index.md', '\n'.join(overview))
    print(json.dumps({k: v for k, v in audit.items() if k != 'excluded_other_author_records'}, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify exact artifacts without writing')
    file_capture(check=parser.parse_args().check)
